### ISSUE TITLE
i've  noticed that some applications don't preserve their geometry.

### ISSUE THREAD

**Issue by manuraj19** [pop-os/cosmic-epoch#1159]
I've  noticed that some applications don't preserve their geometry. That is, if I shrink an application window to a smaller size, when I reopen it later, it does not retain that geometry. firefox is having no such issue,but  apps like chrome , file manager . terminal etc have this problem.

**Comment by Drakulix** [comment]
> I've noticed that some applications don't preserve their geometry.

Not a cosmic-comp issue, we currently have no way to consistenly track geometry of specific windows. This will be fixed with the `xdg-session-management` protocol eventually, but also needs toolkits to be adjusted.

**Comment by atiq-cs** [comment]
Is it fixed by now? Checking in since it's been a while now! This is an important basic feature: user experience is affected!

**Comment by manuraj19** [comment]
I’ve now updated to the latest COSMIC stable build, but the issue still persists.

Several applications (e.g., File Manager, Terminal, Chromium-based browsers) do not restore their previous window geometry after being closed and reopened, while Firefox behaves correctly.

Could you please confirm whether window geometry persistence is still blocked on the xdg-session-management protocol and toolkit support, or if this is expected to be partially working in the stable release?
If there is any tracking issue, roadmap item, or recommended workaround, that information would be very helpful.

Thank you for the continued work on COSMIC.
