### ISSUE TITLE
[BUG] Top Panel Unresponsive on Secondary Monitor After Latest Update

### ISSUE THREAD

**Issue by DenisV94** [pop-os/cosmic-epoch#1167]
After today's latest update, when I try to open any feature on the top panel on the second monitor, nothing opens. The issue only occurs on the secondary monitor, and everything was working correctly until I performed today's apt update. When I click on any icon in the top panel, it simply doesn't do anything.

![image](https://github.com/user-attachments/assets/9c155068-a823-4979-becf-5ed9074e1730)

Thank you for your attention!

**Comment by FlorianPallas** [comment]
same problem here...
some kind of weird displacement of the popups is going on. With a secondary monitor connected I can only interact with the applets on my integrated laptop monitor, but the popups are still displaced.

![image](https://github.com/user-attachments/assets/88735bd5-3655-4235-aca9-fc9a0b932020)

just in case, these are all the packages that I upgraded:
```
cosmic-comp-git (1.0.0.alpha.2.r17.g2497992-1 -> 1.0.0.alpha.2.r20.g0092dac-1)
cosmic-files-git (1.0.0.alpha.2.r166.g2871309-1 -> 1.0.0.alpha.2.r173.g576b9ef-1)
cosmic-randr-git (1.0.0.alpha.1.r0.g71fabbb-4 -> 1.0.0.alpha.1.r5.g907471b-1)
cosmic-settings-git (1.0.0.alpha.2.r40.g2a76db4-1 -> 1.0.0.alpha.2.r49.g537592a-1)
cosmic-term-git (r439.1ed1f41-1 -> r440.8d4bfb9-1)
```

**Comment by bflanagin** [comment]
Same here

Pop!_OS 24.04
hardware: pang12

cosmic-panel 0.1.0\~1729613151\~24.04\~041a44e
cosmic-applets 0.1.0\~1729524303\~24.04\~11faa56

**Comment by DenisV94** [comment]
After using the OS for a few hours, the system becomes increasingly unstable. Occasionally, windows start to glitch across both monitors, and I have to reboot the system to continue using it.

I am using the last POP OS version with nvidia 3080

**Comment by Drakulix** [comment]
> After today's latest update, when I try to open any feature on the top panel on the second monitor, nothing opens. The issue only occurs on the secondary monitor, and everything was working correctly until I performed today's apt update. When I click on any icon in the top panel, it simply doesn't do anything.

Should be fixed by https://github.com/pop-os/cosmic-comp/commit/9a9eddb132a308bd4de17a143e1e4919bfc9c7b1

The update should soon by on the staging branch and then will hopefully also hit the stable repo soon.

**Comment by zsilet** [comment]
@Drakulix Please note that this issue is still reproducible. 
I have added some additional notes into @DenisV94  newly logged issue #1173. 
Previously I was only reproducing the issues on a KVM switch. With the recent introduction of sleep mode on idle, I am noticing that the issue is also happening when the computer comes out of sleep mode.
