### ISSUE TITLE
Java UI buttons aligned improperly

### ISSUE THREAD

**Issue by guusec** [pop-os/cosmic-epoch#1180]
This only occurred after the most recent update of the cosmic-session package for me, and it occurs on multiple java applications when I use cosmic. However it doesn't happen when I use gnome. This leads me to believe that it's something to do with cosmic. To clarify what I mean by java UI buttons, I mean like the Next Tip and Close buttons on this example with Ghidra. This makes a handful of tools I use practically unusable because I'm unable to click the buttons even when focus is on the window.
![java-ui-buttons](https://github.com/user-attachments/assets/431bdeb2-e895-4cbc-8628-3fe7de4cfa17)

**Comment by git-f0x** [comment]
The bottom part of windows that use server-side decorations being unclickable should be fixed by the latest `cosmic-comp` commit.

**Comment by guusec** [comment]
Has this change been pushed to pop repositories yet? After reinstalling cosmic-comp I'm still having the issue.

**Comment by git-f0x** [comment]
If you have `popdev:master` enabled, it's already available.

**Comment by guusec** [comment]
Awesome. It's working now. Thanks a bunch

**Comment by git-f0x** [comment]
It's been reported: #1251
