### ISSUE TITLE
COSMIC session fails to start after latest updates

### ISSUE THREAD

**Issue by d-val-r** [pop-os/cosmic-epoch#1447]
I am not able to log into COSMIC after the latest updates. I am using a Thelio Mira R3 with an AMD Sapphire NITRO+ RX 580.

Updated both firmware on the Thelio and the OS through COSMIC store on January 7th, 2025. Rebooted system. After entering decryption password, screen goes black and stays that way.

After reinstalling Pop!_OS 24.04 from an older build of the alpha ISO that I had on a thumb drive, I saw I could seamlessly reboot. So I'm guessing it's not the firmware. After upgrading the OS through the COSMIC store again and rebooting, the issue returns.

I realized I could get into a TTY from the black screen. I ran `journalctl --user _EXE=/usr/bin/cosmic-session`, and the log shows a variety of errors.

The first error is immediately preceded by a warning:
```
Jan 10 04:59:51 pop-os cosmic-session[1872]: [2025-01-10T04:59:51Z WARN  cosmic_greeter::logind] logind error: org.freedesktop.login1.NoSessionForPID: PID 2051 does not belong to any known session
Jan 10 04:59:51 pop-os cosmic-session[1872]: process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=38 cosmic-greeter ' failed with code 1
Jan 10 04:59:51 pop-os cosmic-session[1872]: cosmic-greeter exited with error 1
```
Subsequent errors occur later in the log, and show the cosmic-files-applet either terminating with signal 15, or exiting with failure code 101.

Installing gdm3 and making it the default display manager lets me at least get to the display manager. If I choose COSMIC session, I get a black screen again. I've got GNOME installed now, and selecting that lets me at least boot into a GUI.

Edit: uploaded logs from `dmesg` and `journalctl -e _COMM=cosmic-comp`.
[cosmic-comp.log](https://github.com/user-attachments/files/18384247/cosmic-comp.log)
[dmesg.log](https://github.com/user-attachments/files/18384248/dmesg.log)

**Comment by elec-n3m** [comment]
I think  this is the same issue I am having. I was able to get to the cosmic-greeter by deleting `~/.local/state/cosmic-comp/outputs.ron` and rebooting. After rebooting I was able to login but only one monitor works even though cosmic-settings detects both. 

output of `journalctl  --user _COMM=cosmic-comp`
```html
Jan 10 09:01:08 pop-os cosmic-comp[2563]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jan 10 09:01:08 pop-os cosmic-comp[2563]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 10 09:01:08 pop-os cosmic-comp[2563]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 10 09:01:08 pop-os cosmic-comp[2563]: Key-Binding 'Period' only matched case insensitive for "period"
Jan 10 09:01:08 pop-os cosmic-comp[2563]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jan 10 09:01:08 pop-os cosmic-comp[2563]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 10 09:01:08 pop-os cosmic-comp[2563]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jan 10 09:01:09 pop-os cosmic-comp[2563]: Unable to become drm master, assuming unprivileged mode
Jan 10 09:01:09 pop-os cosmic-comp[2563]: New screen configuration invalid!:
Jan 10 09:01:09 pop-os cosmic-comp[2563]: Failed to restore modifiers
Jan 10 09:01:09 pop-os cosmic-comp[2563]: using legacy fbadd
Jan 10 09:01:09 pop-os cosmic-comp[2563]: Failed to submit rendering: Failed to submit result for display
Jan 10 09:01:09 pop-os cosmic-comp[2563]: Failed to submit rendering: Failed to submit result for display
Jan 10 09:01:09 pop-os cosmic-comp[2563]: Failed to submit rendering: Failed to submit result for display
Jan 10 09:01:09 pop-os cosmic-comp[2563]: Failed to submit rendering: Failed to submit result for display
Jan 10 09:01:09 pop-os cosmic-comp[2563]: Failed to submit rendering: Failed to submit result for display
```

**Comment by d-val-r** [comment]
Uploaded some logs. I can't help but notice we @git-f0x and I have similar GPUs. One person commenting on pop-os/[cosmic-comp#1124](https://github.com/pop-os/cosmic-comp/issues/1124) also has an RX580. Something to do with our choice of GPUs?

**Comment by elec-n3m** [comment]
> Uploaded some logs. I can't help but notice @git-f0x and I have similar GPUs. One person commenting on [pop-os/cosmic-comp#1124](https://github.com/pop-os/cosmic-comp/issues/1124) also has an RX580. Something to do with our choice of GPUs?

I have a RX580 as well. Probably should have mentioned that. My laptop running cosmic has hybrid graphics and after last update is running fine so it's possible.

**Comment by git-f0x** [comment]
This is likely fixed with the latest commits.

**Comment by d-val-r** [comment]
Updated as soon as I saw they were pushed. This initially did not fix the issue. Logs showed I was missing some config files this time around. I suspected it may have had to do with the fact that I installed a separate DE alongside COSMIC while it was down.

Rebooting to recovery partition and reinstalling, then updating, seems to have fixed the issue. I am able to log in again.
