### ISSUE TITLE
[BUG] Latest COSMIC fails to display anything on the second monitor

### ISSUE THREAD

**Issue by taishi-sama** [pop-os/cosmic-epoch#1456]
OS: Arch Linux [2025.01.11 day update]
Cosmic version: Alpha 5
GPU: Rx590
After starting up COSMIC DE second monitor is turning off(No signal), and if I tried to change any display settings, both monitors got turned off. 
[cosmic-comp.txt](https://github.com/user-attachments/files/18386226/cosmic-comp.txt)
[dmesg.txt](https://github.com/user-attachments/files/18386228/dmesg.txt)

**Comment by git-f0x** [comment]
It's a known issue with Polaris GPUs: https://github.com/pop-os/cosmic-comp/issues/1124

**Comment by git-f0x** [comment]
This is likely fixed with the latest commits.

**Comment by FF-AntiK** [comment]
I'm experiencing this issue with an AMD RX 6700 XT.
It seems to be a timing related issues, because sometimes both Displays work, sometimes only one of them.

**Comment by kjcole** [comment]
Still present in Beta... (Alpha identified and used the second monitor for a while, but now it's identifying it as `Unknown 10"` when previously both 22.04 LTS and 24.04 Alpha knew it as a `Dell 2?"` (I forget 24" I think.)
