### ISSUE TITLE
the place  of cursor is offset

### ISSUE THREAD

**Issue by xingyaoc-1999** [pop-os/cosmic-epoch#1541]
When I program with lazyvim, sometimes the mouse position is normal, sometimes there is a deviation of a space

**Comment by RoyalOughtness** [comment]
Seeing this as well. Sometimes it's fine, sometimes it's a pixel or two horizontally offset. Makes using an IDE a bit tricky 🙂

**Comment by Drakulix** [comment]
If this only affected Xwayland applications, this is likely fixed by https://github.com/pop-os/cosmic-comp/commit/61bde9f3b9941cadb87978ff58ec019653394d02

**Comment by xingyaoc-1999** [comment]
> If this only affected Xwayland applications, this is likely fixed by [pop-os/cosmic-comp@61bde9f](https://github.com/pop-os/cosmic-comp/commit/61bde9f3b9941cadb87978ff58ec019653394d02)"I found that even in terminal programs, the offset still exists."

**Comment by xingyaoc-1999** [comment]
![Image](https://github.com/user-attachments/assets/30847486-5c6d-4ffd-bae9-0a4c41214de7)

I found that even in terminal programs, the offset still exists.

**Comment by Drakulix** [comment]
That is an unrelated cosmic-term issue. Please open another there.
