### ISSUE TITLE
The app library doesn't open when the panel is on the left or right

### ISSUE THREAD

**Issue by fierce-goose** [pop-os/cosmic-epoch#1744]
It works fine when the panel is on the top or bottom. I use NixOS btw

**Comment by git-f0x** [comment]
This has been fixed last week.

**Comment by DikshitRJ** [comment]
I opened the same issue, and the developers actively fixed it. Update Cosmic in nixos, it will be alright.

I suggest you close the issue. Duplicate of #1726

**Comment by fierce-goose** [comment]
> I opened the same issue, and the developers actively fixed it. Update Cosmic in nixos, it will be alright.
> 
> I suggest you close the issue. Duplicate of [#1726](https://github.com/pop-os/cosmic-epoch/issues/1726)

but I updated it right before opening the issue, and the app library still doesn't open if the panel is on the side
