### ISSUE TITLE
Panel and Bar do not show some icons when using the COSMIC icon pack—no icons for COSMIC apps appear when using another icon pack

### ISSUE THREAD

**Issue by KainAlive** [pop-os/cosmic-epoch#2057]
**Describe the bug**
All COSMIC apps show gray cogs instead of icons in the dock and app launcher. When using the COSMIC icon pack, this also applies to most other apps. When switching to another icon pack (like Papyrus), icons for most non-COSMIC apps return, but apps like COSMIC Files, COSMIC Settings, etc., only show the gray cog icon.

In the panel, icons for notifications, Bluetooth, battery, and tiling are completely blank (they occupy the space but show no icons). The same goes for the "Launcher," "Workspaces," and "Applications" buttons in the dock.

**Expected behavior**
Icons should render correctly.

**Screenshots**
![Image](https://github.com/user-attachments/assets/f5b2b218-60e8-49ec-bb18-b2f70c88fde5)

![Image](https://github.com/user-attachments/assets/a660f585-d9e8-45b8-bd06-7cfe56ac7e87)

![Image](https://github.com/user-attachments/assets/bdcaafa3-5924-4547-acd2-51f1ed989765)

(Sorry for the bad images, but cosmic-screenshot crashes currently, so I have to take a photo of my monitor.)

**Desktop (please complete the following information):**
 - OS: NixOS unstable; also happens on stable

**Additional context**
This happens with the official COSMIC package from nixpkgs and with the [cosmic flake by lilyinstarlight](https://github.com/lilyinstarlight/nixos-cosmic).

It did not happen the first time I installed COSMIC about six months ago, but since then, I have faced this exact problem.

**Comment by mmstick** [comment]
You should report it to NixOS. App and applet icons are bundled in the packaging of the apps themselves. The cosmic icon theme does not contain any app icons. Only additional symbolic icons used by cosmic apps and applets. Also make sure you have the Pop and hicolor icon theme packages installed.

**Comment by KainAlive** [comment]
I will also report it to NixOS, but I'm not sure that the packaging is the problem, as a friend of mine with the exact same laptop, also on NixOS unstable, does not have any of these problems. So I guess the packaging is working correctly.

**Comment by KainAlive** [comment]
To add to that, it does not work when switching to an icon pack that has the correct icons for the application (for example, "cosmic-applications," which is also part of the Papirus icon theme); it still won't render the icon. Not just a cog icon, but completely blank (see the screenshot above). In my case, the icon for Papirus pop-cosmic-applications is installed at `~/.local/share/icons/Papirus/22x22/apps/pop-cosmic-applications.svg`.

Also, the fact that the icons in the dock and bar are completely blank leads me to believe that this is a weird rendering error, not an icon packaging error.

**Comment by KainAlive** [comment]
Another thing I noticed is that other launchers like fuzzel render the icons correctly (see the screenshot), so I really don't think this is a packaging problem, but more of a rendering problem.

![Image](https://github.com/user-attachments/assets/c1fb4fae-9f18-498b-a98d-7cc6609e97d5)

**Comment by vtuber-coffee** [comment]
adding to this, there appear to be two parts to the blank icon issue. 

1. icons are not selected from the correct folders/priority. i had a copy of BeautyLine in both ~/.local/share/icons... and /usr/share/icons. linking appropriate icons to the expected filenames in ~/.local had no effect on improperly displaying cosmic apps. i could only get the icons to display correctly by making the modifications in/usr/share/icons .  https://specifications.freedesktop.org/icon-theme/latest/ seems to suggest that icons sets in ~/.local/share/icons should take priority over icon sets in /usr/share/icons

2. links to icons are not reliable. the linked versions of icons that shipped with the theme worked correctly. creating new links for cosmic apps did not work at all with any combination of restarting the dock/logging out & in/rebooting. there appears to be no way to refresh the icon cache. cp original-file.svg to com.system76.CosmicApp.svg in /usr/share/icons was how i got the icons to display correctly; this did not work in ~/.local/share/icons . thinking back, it's possible that selecting any other theme and returning to the modified theme might have forced a refresh but there's no way to tell now

**Comment by vtuber-coffee** [comment]
for clarity, my instance of the issue happened on arch, not nix. it does not appear to be a distribution specific issue. 

the issue was solved in the past by creating links in /usr/share/icons; the issue returned after a recent update to cosmic components and links stopped working entirely. the links could be opened into an image viewer and displayed the linked icons correctly before replacing them with copies of the icon files

**Comment by tonyfarson** [comment]
### 🔍 Finding: COSMIC icon cache issue affects both Chrome PWAs *and* Flatpak apps

While investigating missing / placeholder (“gear”) icons for **Chrome PWAs** on **Pop!_OS 24.04 with COSMIC**, I discovered the same root cause also affects **Flatpak-installed applications**.

---

### ✅ What’s actually happening

- Both **Chrome (apt & Flatpak)** and **Flatpak apps** correctly:
  - Create `.desktop` files under  
    `~/.local/share/applications/`
  - Install icon PNGs under  
    `~/.local/share/icons/hicolor/<size>/apps/`
- The `.desktop` files reference valid icon names
- **Despite this**, COSMIC shows a generic placeholder icon

So the issue is **not missing icons** and **not malformed desktop files**.

---

### 🧠 Root cause (observed)
COSMIC does not appear to automatically rebuild or refresh the **user GTK icon cache** when new icons are added to the local `hicolor` theme.

As a result, icon lookups fail until the cache is manually rebuilt.

---

### 🛠️ Workaround / Fix

Running the following command immediately resolves the issue:

```bash
gtk-update-icon-cache -f -t ~/.local/share/icons/hicolor

**Comment by KainAlive** [comment]
@tonyfarson Didn't work for me. It still does not render the icons correctly, even when rebuilding the cache for all icons I have installed

**Comment by vtuber-coffee** [comment]
@KainAlive that fix is likely for the version of cosmic that is a essentially a very customized gnome

the main points of current cosmic are to not have to manually implement things gnome are actively working against in their project and to build everything from scratch in rust, so i'd be surprised if gtk-update-icon-cache would do anything to how current cosmic handles icons

**Comment by KainAlive** [comment]
@vtuber-coffee makes sense I guess. The funny thing is that the issue was magically fixed after an update on my desktop PC, but still persists on my Laptop. I really do not understand why that is, as I share the nix config between both. But launchers like Vicinae also have problems finding the correct icons on that laoptop while working perfectly fine on the desktop PC. So this might not be just a COSMIC problem

**Comment by vtuber-coffee** [comment]
@KainAlive however, i get the same behavior specifically on cosmic apps on arch across several systems. the main commonality seems to be cosmic. do you use the default icon set? i don't, and was only able to correct the issue by copying svg images to the expected folder and filename in /usr/share/icons. links to files would not work, and placing new files / links in any other expected path defined by the freedesktop standard also didn't work. the problem is also only with cosmic apps and does not exist when starting a different desktop session on the same machines

**Comment by KainAlive** [comment]
Update:
I think I fixed it. It turned out I had following in one of my custom packages:

      postInstall = ''
        # Skip icon cache update during build
        export DESTDIR="/"
        sed -i '/gtk-update-icon-cache/d' build-aux/meson/postinstall.py
        sed -i '/update-desktop-database/d' build-aux/meson/postinstall.py

        # Create empty theme index if it doesn't exist
        touch $out/share/icons/hicolor/index.theme

        # Compile schemas if they exist
        if [ -d "$out/share/glib-2.0/schemas" ]; then
          glib-compile-schemas "$out/share/glib-2.0/schemas"
        fi
      '';
I am not sure what caused the issue here, but removing this fixed the icons on my laptop.

**Comment by dopreo** [comment]
> Update: I think I fixed it. It turned out I had following in one of my custom packages:
> 
> ```
>   postInstall = ''
>     # Skip icon cache update during build
>     export DESTDIR="/"
>     sed -i '/gtk-update-icon-cache/d' build-aux/meson/postinstall.py
>     sed -i '/update-desktop-database/d' build-aux/meson/postinstall.py
> 
>     # Create empty theme index if it doesn't exist
>     touch $out/share/icons/hicolor/index.theme
> 
>     # Compile schemas if they exist
>     if [ -d "$out/share/glib-2.0/schemas" ]; then
>       glib-compile-schemas "$out/share/glib-2.0/schemas"
>     fi
>   '';
> ```
> 
> I am not sure what caused the issue here, but removing this fixed the icons on my laptop.

Please elaborate :') having a similar issue on Cachy, and wanna know how to fix it. Thank you :)
