### ISSUE TITLE
clicking "open containing folder" in slack (flatpak) hangs for ~30 seconds

### ISSUE THREAD

**Issue by ellieplayswow** [pop-os/cosmic-epoch#2154]
**Describe the bug**
this started happening today, i'm unsure which component is responsible, sorry!

when downloading a file in slack, i click "open containing folder" and would normally expect the files app to open very shortly after. 

```
Sep 17 09:30:33 pop-os cosmic-comp[4790]: [GL] GL_INVALID_VALUE error generated. Size and/or offset out of range.
Sep 17 09:30:39 pop-os cosmic-comp[4790]: Failed to handle X11 event
Sep 17 09:31:05 pop-os xdg-desktop-por[5115]: Failed to call ShowItems: Timeout was reached
Sep 17 09:31:05 pop-os com.system76.CosmicFiles.desktop[16913]: [2025-09-17T08:31:05Z WARN  wgpu_hal::gles::egl] No config found!
```

i'm unsure if this bug is in cosmic-files-applet, xdg-desktop-portal-cosmic or perhaps in the actual xdg-desktop-portal executable

**To Reproduce**
1. download a file from slack
2. click "open containing folder"

this also happens in firefox (system), but to a much lesser extent (hangs for ~2-3 instead)

**Expected behavior**
i would expect the cosmic-files app to open reasonably quickly as has been the case in the past

**Screenshots**
n/a

**Desktop (please complete the following information):**
- pop!_os 24.04
- nvidia drivers 575.64.05
- kernel 6.16.3-76061603-generic

```
cosmic-app-library/noble,now 0.1.0~1757355962~24.04~893fe70 amd64 [installed,automatic]
cosmic-applets/noble,now 0.1.0~1757964151~24.04~8196fc6 amd64 [installed,automatic]
cosmic-bg/noble,now 0.1.0~1756826102~24.04~6841c5a amd64 [installed,automatic]
cosmic-comp/noble,now 0.1~1757920380~24.04~b83e9f1 amd64 [installed,automatic]
cosmic-edit/noble,now 0.1.0~1758034657~24.04~099e32b amd64 [installed,automatic]
cosmic-files/noble,now 0.1.0~1757971256~24.04~436b8b3 amd64 [installed,automatic]
cosmic-greeter-daemon/noble,now 0.1.0~1758036505~24.04~31912af amd64 [installed,automatic]
cosmic-greeter/noble,now 0.1.0~1758036505~24.04~31912af amd64 [installed,automatic]
cosmic-icons/noble,now 0.1.0~1757977193~24.04~70b0758 amd64 [installed,automatic]
cosmic-idle/noble,now 0.1.0~1740507204~24.04~267bb83 amd64 [installed,automatic]
cosmic-initial-setup/noble,now 0.1.0~1758037746~24.04~55c6006 amd64 [installed,automatic]
cosmic-launcher/noble,now 0.1.0~1757600046~24.04~ee52edd amd64 [installed,automatic]
cosmic-notifications/noble,now 0.1.0~1757447875~24.04~3c2a10a amd64 [installed,automatic]
cosmic-osd/noble,now 0.1.0~1757712881~24.04~8c35926 amd64 [installed,automatic]
cosmic-panel/noble,now 0.1.0~1758037363~24.04~9ab63d6 amd64 [installed,automatic]
cosmic-player/noble,now 0.1.0~1757967471~24.04~5556cf8 amd64 [installed,automatic]
cosmic-randr/noble,now 0.1.0~1757248943~24.04~bce9cdf amd64 [installed,automatic]
cosmic-screenshot/noble,now 0.1.0~1758044304~24.04~dc054dc amd64 [installed,automatic]
cosmic-session/noble,now 0.1.0~1757100934~24.04~2441be2 amd64 [installed,automatic]
cosmic-settings-daemon/noble,now 0.1.0~1757703022~24.04~ee782f4 amd64 [installed,automatic]
cosmic-settings/noble,now 0.1.0~1757977254~24.04~bb0fb95 amd64 [installed,automatic]
cosmic-store/noble,now 0.1.0~1757971203~24.04~2c9d437 amd64 [installed,automatic]
cosmic-term/noble,now 0.1.0~1757971274~24.04~a814c82 amd64 [installed,automatic]
cosmic-wallpapers/noble,noble,now 1.0.0~1744123997~24.04~189c2c6 all [installed,automatic]
cosmic-workspaces/noble,now 0.1.0~1758040496~24.04~3aad95d amd64 [installed,automatic]
pop-de-cosmic/noble,now 3.0.0~1753752915~24.04~e5746df amd64 [installed,automatic]
xdg-desktop-portal-cosmic/noble,now 0.1.0pop1~1757647525~24.04~a069d57 amd64 [installed,automatic]
```

**Additional context**

**Comment by PhoenixPhantom** [comment]
I'm also experiencing this since about a week.
I've primarily noticed it happening on Brave (native package) as I'm using it  often, but it also occurs on the Electron apps Signal (Flatpak) and Obsidian (Flatpak). For me, clicking "Show in Folder" takes equally long (about 25s) on all of these apps. 

In addition to the long duration, the app that eventually opens in my case is not even cosmic-files but zathura. I have checked `xdg-mime query default inode/directory` and it returns `com.system76.CosmicFiles.desktop` as I'd expect. Also `xdg-open .` still opens cosmic-files immediately. The wrong application being opened from these apps only started happening for me when "Show in Folder" started taking longer, so the two problems may be related.

**Desktop**
NixOS 25.11
AMD 890M GPU on Mesa 25.2.3
Kernel 6.16.7

**Comment by Minoscereb** [comment]
Same thing happens in Vivaldi, whether installed as a system app or flatpak on 24.04 with all updates installed as of today, September 28, Nvidia driver 580.82.07.

**Comment by PhoenixPhantom** [comment]
I've just updated to the latest master branch of all components (as of the 18. Oct; The prior versions I used are from about 2d ago) and for me, the issue seems fixed now. (Both the delay and it opening the wrong application)
I'm not sure which component update exactly fixed it for me though...

**Comment by ellieplayswow** [comment]
interesting! it still hangs for me:
```
cosmic-app-library/noble,now 0.1.0~1760625080~24.04~42dfbea amd64 [installed,automatic]
cosmic-applets/noble,now 0.1.0~1760625623~24.04~086f501 amd64 [installed,automatic]
cosmic-bg/noble,now 0.1.0~1760286723~24.04~f1f79d3 amd64 [installed,automatic]
cosmic-comp/noble,now 0.1~1760619582~24.04~bead74f amd64 [installed,automatic]
cosmic-edit/noble,now 0.1.0~1760644502~24.04~913fd8b amd64 [installed,automatic]
cosmic-files/noble,now 0.1.0~1760586202~24.04~acf5295 amd64 [installed,automatic]
cosmic-greeter-daemon/noble,now 0.1.0~1760586274~24.04~fec5ffe amd64 [installed,automatic]
cosmic-greeter/noble,now 0.1.0~1760586274~24.04~fec5ffe amd64 [installed,automatic]
cosmic-icons/noble,now 0.1.0~1757977193~24.04~70b0758 amd64 [installed,automatic]
cosmic-idle/noble,now 0.1.0~1740507204~24.04~267bb83 amd64 [installed,automatic]
cosmic-initial-setup/noble,now 0.1.0~1760463495~24.04~0080330 amd64 [installed,automatic]
cosmic-launcher/noble,now 0.1.0~1760637270~24.04~5ad1bfb amd64 [installed,automatic]
cosmic-notifications/noble,now 0.1.0~1760020147~24.04~07d40a7 amd64 [installed,automatic]
cosmic-osd/noble,now 0.1.0~1760286168~24.04~91930fc amd64 [installed,automatic]
cosmic-panel/noble,now 0.1.0~1760458336~24.04~f1a9476 amd64 [installed,automatic]
cosmic-player/noble,now 0.1.0~1760446719~24.04~37cea24 amd64 [installed,automatic]
cosmic-randr/noble,now 0.1.0~1757248943~24.04~bce9cdf amd64 [installed,automatic]
cosmic-screenshot/noble,now 0.1.0~1760446590~24.04~8ca2c6a amd64 [installed,automatic]
cosmic-session/noble,now 0.1.0~1758302814~24.04~379ce30 amd64 [installed,automatic]
cosmic-settings-daemon/noble,now 0.1.0~1759848319~24.04~6833138 amd64 [installed,automatic]
cosmic-settings/noble,now 0.1.0~1760625555~24.04~ae4a2a7 amd64 [installed,automatic]
cosmic-store/noble,now 0.1.0~1760446616~24.04~9b6f8b6 amd64 [installed,automatic]
cosmic-term/noble,now 0.1.0~1760462416~24.04~8c409f5 amd64 [installed,automatic]
cosmic-wallpapers/noble,noble,now 1.0.0~1744123997~24.04~189c2c6 all [installed,automatic]
cosmic-workspaces/noble,now 0.1.0~1760286703~24.04~b7afe23 amd64 [installed,automatic]
pop-de-cosmic/noble,now 3.0.0~1753752915~24.04~e5746df amd64 [installed,automatic]
xdg-desktop-portal-cosmic/noble,now 0.1.0pop1~1760462435~24.04~43572e6 amd64 [installed,automatic]
```
@PhoenixPhantom , do you note anything different between our versions? maybe that helps narrow it down :)

**Comment by PhoenixPhantom** [comment]
Hi @ellieplayswow
I'm not 100% sure what every part of your output means ;)

But I hope I am correct in assuming that the second number (i.e. `1760462435` for `xdg-desktop-portal-cosmic/noble,now 0.1.0pop1~1760462435~24.04~43572e6 amd64 [installed,automatic]`) is a unix timestamp. If so and it indicates the time your version was released, that would mean that your version is from e.g. `1760462435` (2025-10-14 17:20:35) which is a few days older than the versions that solved the problem for me.

Looking at the other timestamps, the newest update seems to have been on the 2025-10-16, so probably the pop os packages have not yet been rebuilt with the commits from the last three days. But probably they will be soon :)

This does validates my initial impression that the fix (if the change indeed fixes it for everyone) was only pushed in the last two or three days. The changes to xdg-desktop-portal-cosmic on the 17th seemed particularly notable to me and may well be related but it might also have been due to some other change.

**Comment by ellieplayswow** [comment]
my output is from `apt list --installed | grep cosmic`, i'm unsure how the versioning works but i know the end is the commit hash (eg, im on commit `43572e6` for `xdg-desktop-portal-cosmic`), will check in a few days when some new updates get pushed to the apt repo :)

**Comment by ellieplayswow** [comment]
fixed now as of 2025-10-24
