### ISSUE TITLE
Support for Custom Keyboard Layouts in Cosmic DE Beta

### ISSUE THREAD

**Issue by mateowoetam** [pop-os/cosmic-epoch#2175]
**Is your feature request related to a problem? Please describe.**  
I'm currently testing my [custom keyboard layout script](https://codeberg.org/mateowoetam/halmaklinuxsupport/) with the Cosmic DE Beta release. While the script runs without issues, I am frustrated that the DE does not seem to read keyboard layouts from the `/home/$USER/.config/xkb/` directory. As a result, my custom layout does not appear in the layout selector, limiting its usability.

**Describe the solution you'd like**  
I would like the Cosmic DE team to investigate and implement support for reading custom keyboard layouts from the `/home/$USER/.config/xkb/` directory. This would allow users to easily access and select their custom layouts without needing to install them in `/usr/share/X11/xkb/`, which, in the case of the Cosmic Beta, also does not work.

**Describe alternatives you've considered**  
Currently, my script offers two installation methods: one that installs layouts in the home `.config` directory and another that installs them in `/usr/share/X11/xkb/`. While the latter often resolves visibility issues in other desktop environments, it does not work in the Cosmic Beta.

**Additional context**  
[My custom layout](https://codeberg.org/mateowoetam/halmaklinuxsupport/) is not yet included in the XKeyboardConfig layout library, making this feature particularly important for users who want to utilize custom layouts in Cosmic DE. I am not well-informed on how to create custom keyboard layouts in Wayland since `setxkbmap` doesn't work. I've been using KDE with XWayland and also in Gnome, and other DEs I've tested are detailed in my repo. Interestingly, my script only works in the `/home` mode inside Wayland with XWayland and not in Xorg DEs.

Thank you for considering this request!

**Comment by ScratchingDog** [comment]
I have the same problem. My layout and scripts were working in Alpha 7.
After updating, the layout kept working until I changed the keyboard-related settings in the GUI. Now it works in the TTY but not in the desktop environment.

For clarification: in Alpha 7 it never worked on the login screen (it assigned me QWERTY) until I logged in with my user. Once I was logged in, if I locked the screen, suspended, or hibernated, I could then use my layout on the login screen.

**Comment by Skyrocket1653** [comment]
I have similar problem. In my case it does not pick up my custom keyboard layout when I have added `symbols/bluewy` and modified `rules/evdev.xml`. Plasma does pick up my custom keyboard layout. Futhermore, the cosmic-greeter seems to show an empty keyboard layout list if manually defining in the config and is working in the desktop.

**Comment by ScratchingDog** [comment]
I solved the problem. Take a look to my repo:
[https://github.com/ScratchingDog/DvorakProgrammerES](https://github.com/ScratchingDog/DvorakProgrammerES)

**Comment by vazub** [comment]
I have the same issue as the original reporter. Cosmic does not seem to be parsing `~/.config/xkb/`, so no custom keyboard layouts can be picked up in keyboard settings. Which is strange, as this functionality should be handled by `libxkbcommon` which Cosmic seems to rely on. Switching back to KDE (I am using both on OpenSUSE Tumbleweed) - everything works fine, as expected.

**Comment by mateowoetam** [comment]
The issue still persists when using only the userspace directories.
> I solved the problem. Take a look to my repo: [github.com/ScratchingDog/DvorakProgrammerES](https://github.com/ScratchingDog/DvorakProgrammerES)

Unfortunately, this approach didn’t work for me. I’ve been trying to avoid the root directory as I focus on more immutable systems like those based on uBlue or NixOS.

Using `~/.config/xkb/` is still not functioning in version 1.0.2; the desktop environment doesn’t recognize that it can parse that directory.

p.s. for anyone interested I've been maintaining my own xkb keyboard layout installation script for different Distros and DE: [aklinux](https://codeberg.org/mateowoetam/aklinux)

**Comment by ahinkka** [comment]
Seems like this has been resolved in https://github.com/pop-os/xkb-data/pull/8. I got my keyboard working with the instructions in the PR.

**Comment by AvianAnalyst** [comment]
I'm not sure how to check if I have that change in my versions. I've fully updated my system in sync with Arch/CachyOS. Here's my cosmic versions: 

<img width="900" height="656" alt="Image" src="https://github.com/user-attachments/assets/ac399bca-4cd8-4f47-a03e-a7582a7ec071" />

I'm able to pick up the banana layout, but it doesn't seem to function as described (pressing 4 gives me 4 not $ and with orange pressing 5 gives me 5 and S-5 gives me %) 

<img width="2048" height="1248" alt="Image" src="https://github.com/user-attachments/assets/f0b7f5cb-38ef-4f84-949e-767f20b81beb" /> Here you can see the file, its location, and that I have the orange variant selected as my current keyboard.

**Comment by AvianAnalyst** [comment]
Ok I removed and readded the keyboard layouts in my input settings. now banana works but orange still doesn't. 

I'm also getting all of these: 

<img width="2048" height="1248" alt="Image" src="https://github.com/user-attachments/assets/8e29ba5a-4c26-4992-b0eb-a30643de918f" />
