### ISSUE TITLE
Single click on Chrome's tab/title area unmaximizes window

### ISSUE THREAD

**Issue by rmergeee** [pop-os/cosmic-epoch#2193]
**Describe the bug**
When using Google Chrome on COSMIC Epoch Beta 1, a single click on the tab bar or title bar area causes the window to unmaximize (toggle from maximized to windowed).
Normally this behavior only happens on double click, not on single click.

**To Reproduce**
1. Open Google Chrome (stable or beta).
2. Maximize the Chrome window.
3. Click once on the tab bar / title bar area.
4. The window immediately unmaximizes.

**Expected behavior**
A single click should only focus the window and do nothing else.
The window should remain maximized until explicitly unmaximized (by double click or dragging).

**Desktop:**
- OS: Pop!_OS 24.04 (COSMIC Epoch Beta 1)
- Display server: Wayland & X11 (both tested, same behavior)
- Application: Google Chrome (Google Chrome 140.0.7339.207 and google-chrome-unstable and chromium)

**Additional context**
- The bug only appears in Chrome/Chromium; other applications behave correctly.
- Toggling “Use system title bar and borders” in Chrome does not fix the issue — the tab strip area still unmaximizes the window.

**Comment by trisweb** [comment]
+1

And a double-click on a non-maximized window sometimes instantly moves the window over 10-40px, making it not possible to maximize by double-clicking.

**Comment by ShyVortex** [comment]
+1

**Comment by Hen0k** [comment]
+1

**Comment by jwoertink** [comment]
I think https://github.com/pop-os/cosmic-epoch/issues/832 may be related?

**Comment by rhessus** [comment]
I have the same issue, and it also happens with Cursor IDE. When I single-click the title bar of Cursor, it exits maximized mode.

**Comment by lincolnthalles** [comment]
+1

It's still happening and there are similar open issues.

The title bar should trigger the window moving action only after a click + drag event. It's triggering it with a single click, or there's no debouncing for the drag.

This makes it TOO sensitive, interfering with apps that join controls in the title bar, like many browsers do. It also affects some Qt apps like Kate, which don't join things in the title bar, but a single click does the same thing.

It doesn't affect most apps with a standard window title bar and doesn't affect any libadwaita apps. On those, the window move action only starts if you intentionally click and drag.

It's bad both with and without tiling, though having the affected app as the sole tiled window mitigates the annoyance, as it will blink, but the window manager will move it back where it was.

**Comment by rhessus** [comment]
This anomaly appears to have been resolved. I no longer have the issue on Chrome, Lens, or Cursor. Thank you.

**Comment by jwoertink** [comment]
I still see the issue on Chrome and Discord... Is there a specific update, @rhessus ?

**Comment by rhessus** [comment]
> I still see the issue on Chrome and Discord... Is there a specific update, [@rhessus](https://github.com/rhessus) ?

I just did the last system updates yesterday

**Comment by jwoertink** [comment]
Ah! I just updated and you're right, @rhessus, chrome isn't doing it anymore! 🎉

**Comment by lincolnthalles** [comment]
It's **_much_** better now, but it's still a little bit too sensitive.

**Comment by rhessus** [comment]
@leviport we can close this issue ?

**Comment by leviport** [comment]
Thanks for the reminder!
