### ISSUE TITLE
Cannot add custom images as wallpapers using the settings

### ISSUE THREAD

**Issue by Adhvay0505** [pop-os/cosmic-epoch#2442]
**Describe the bug**
Unable to add images as wallpapers using the COSMIC settings, this fails by right clicking the "Change Wallpaper" option from the desktop, or by going to the wallpaper settings directly. 

**To Reproduce**
1. Desktop > Wallpaper > Add Image > Select Image > It fails, default wallpaper remains
2. There is also no available option to set the wallpaper from the default COSMIC file manager by clicking on the image of choice

**Expected behavior**
This option should allow users to select images into the default set of wallpapers, and then set it as the Wallpaper, however this does not work, The only way to set the wallpaper that worked is by going to `/home/user/.config/cosmic/com.system76.CosmicBackground/v1` and setting the path to the image I want to set as the wallpaper in the config file

**Desktop (please complete the following information):**
 - OS: Fedora 43 cosmic spin
- DE: COSMIC Beta

**Comment by jordonedavidson** [comment]
When using PopOS 24.04 with cosmic beta the  Add Image button in the Desktop | Wallpaper settings panel is non functional .Clicking gives no response whatsoever. 

System:
 OS: Pop!_OS 24.04 LTS x86_64
 Host: KVM/QEMU Standard PC (Q35 + ICH9, 2009) (pc-q35-7.0)
 Kernel: Linux 6.16.3-76061603-generic
 Uptime: 5 mins
Packages: 1659 (dpkg), 14 (flatpak-user)
 Shell: zsh 5.9
 Display (QEMU Monitor): 1920x1080 in 15", 60 Hz
 DE: COSMIC
 Theme: Yaru [GTK3]
 Icons: Yaru [GTK3]
Cursor: Adwaita
Terminal: cosmic-term
 CPU: 4 x 11th Gen Intel(R) Core(TM) i5-1135G7 (4) @ 2.42 GHz
GPU: RedHat Virtio 1.0 GPU
 Memory: 2.16 GiB / 7.75 GiB (28%)
Swap: 0 B / 11.75 GiB (0%)
  Disk (/): 13.44 GiB / 35.13 GiB (38%) - ext4
  Locale: en_CA.UTF-8`

**Comment by Adhvay0505** [comment]
After a major update to COSMIC desktop elements on Fedora 43 COSMIC Spin, I’ve tested this again while running COSMIC 1.0.0~beta.5. I expected this issue to be resolved, but unfortunately, it still persists.

- Adding new images via Desktop → Change Wallpaper → Add Image still fails.
- The wallpaper list doesn’t update, and the default wallpaper remains applied.

The only current workaround (I think) is to edit the path in the file:
`~/.config/cosmic/com.system76.CosmicBackground/v1`

**Comment by Adhvay0505** [comment]
> When using PopOS 24.04 with cosmic beta the Add Image button in the Desktop | Wallpaper settings panel is non functional .Clicking gives no response whatsoever.
> 
> System: OS: Pop!_OS 24.04 LTS x86_64 Host: KVM/QEMU Standard PC (Q35 + ICH9, 2009) (pc-q35-7.0) Kernel: Linux 6.16.3-76061603-generic Uptime: 5 mins Packages: 1659 (dpkg), 14 (flatpak-user) Shell: zsh 5.9 Display (QEMU Monitor): 1920x1080 in 15", 60 Hz DE: COSMIC Theme: Yaru [GTK3] Icons: Yaru [GTK3] Cursor: Adwaita Terminal: cosmic-term CPU: 4 x 11th Gen Intel(R) Core(TM) i5-1135G7 (4) @ 2.42 GHz GPU: RedHat Virtio 1.0 GPU Memory: 2.16 GiB / 7.75 GiB (28%) Swap: 0 B / 11.75 GiB (0%) Disk (/): 13.44 GiB / 35.13 GiB (38%) - ext4 Locale: en_CA.UTF-8`

this bug preventing users from adding a wallpaper via the Settings on Cosmic via the Add Image button has been fixed, with the latest update to cosmic on fedora 43's cosmic spin. Add Image button now works as expected.

**Comment by linuzzz** [comment]
I just did a system upgrade on my Fedora 43 Cosmic spin and the bug is still there :-(

**Comment by hertz98** [comment]
~Updated Pop!_OS 24.04 Beta, same~

~Also selecting the Wallpaper Menu and selecting `Open new folder` does nothing~

EDIT: Updated today, it works fine

**Comment by leviport** [comment]
Working for me as well. Anyone else seeing it fixed?

**Comment by Adhvay0505** [comment]
> Working for me as well. Anyone else seeing it fixed?

yes, should be fixed for all users, considering the official release is almost here, works fine for me
