### ISSUE TITLE
Visual artifacts/tearing when using display-link hardware in portrait mode

### ISSUE THREAD

**Issue by scottmckendry** [pop-os/cosmic-epoch#2444]
**Describe the bug**
When using a display driven by displaylink/evdi hardware (most USB-C docks), there is significant artifacting, and the bottom half of the display doesn't get updated.

This does not happen for regular outputs, nor does it happen for displaylink outputs in their preferred orientation.

Unfortunately, this does not appear in screenshots or screen recordings, hence the pictures of my physical display.  

**To Reproduce**
1. Using a displaylink dock & monitor, set the output to portrait mode. 
2. Move a window around on the rotated display, interact with it etc.
3. Issue should be fairly apparent at this point. 

**Expected behavior**
Window should be rendered correctly without tearing, and the bottom half of the screen should update on each frame as the content changes. 

**Screenshots**
<img width="1215" height="910" alt="Image" src="https://github.com/user-attachments/assets/cf7a1b89-8e83-41ee-97c5-042f0aa59866" />

**Desktop (please complete the following information):**
 - OS: NixOS 25.05

**Comment by kocherjj** [comment]
I can confirm this is happening for me as well. My workstation is setup with two Displaylink monitors in Portrait mode flanking an ultra-wide driven by Displayport Alt Mode.
This has worked well for me with Manjaro Linux for 6 years, but I've been wanting to move to PopOS Cosmic for several reason and was excited to see the reports that Displaylink works now since it did not several months ago.

I tried it again today and observed the same issue reported above. The monitors are completely unusable. Large sections are grayed out and the parts that are not do not update smoothly but show artifacts similar to that shown above.

This is with a fresh install of PopOS 24.04 Beta on a Thinkpad E16 G2 with a Ryzen 7735HS CPU, fully updated, nothing added except the Synaptic Displaylink PPA and driver.

When I change the Displaylink Monitors to landscape mode in the settings they seem to operate smoothly, like they do in Portrait mode on my Manjaro daily driver.

**Comment by benfrussell** [comment]
Adding another occurrence of visual issues in portrait mode over DisplayLink. This occurred in a fresh install, after installing the [Synaptics DisplayLink Ubuntu Driver](https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu) (the monitor was not detected prior to that).

The issues occur only in the top half of the display. In my case the rotation is at 270 deg to orient the display correctly. If I rotate by 90 deg instead, the issue now occurs at the 'physical bottom' of the display rather than the 'physical top'.

![Image](https://github.com/user-attachments/assets/a4352729-3b45-4373-abca-8346e54c7956)

The issues consist of very slow display updates (~3 seconds) and occasional tearing of the cursor or displayed windows.

**OS:** Pop!_OS 24.04 LTS Beta
**Hardware:** [HP USB-C Universal Dock](https://support.hp.com/ca-en/product/details/hp-usb-c-docking-station/model/17032734)

**Comment by Nishan-Vivek** [comment]
Also having the same issue on my two flanking portrait monitors on a displaylink hub . Tearing laggy and cursor  and windows don't display at all on 1/3 of the displays. Latest popos updates and synaptics Ubuntu driver as of December 26th.

If anyone knows where to start for log gathering or any other steps for this issue let me know .

**Comment by Megatrxn** [comment]
The issue is still there. The Portrait mode is unusable.

**Comment by weberam2** [comment]
Same here :(
I tried updating the displaylink driver etc...

**Comment by Nishan-Vivek** [comment]
Has anyone with this issue been able to build and test the latest evdi driver?
https://github.com/DisplayLink/evdi/releases

**Comment by weberam2** [comment]
I have the latest:
```
❯ dpkg -l | grep evdi
ii  evdi                                                     1.14.15-181                                                       amd64        Extensible Virtual Display Interface (EVDI) is a Linux® kernel module that enables management of multiple screens.
```

Other info:
```
OS: Pop!_OS 24.04 LTS x86_64
Host: Bonobo WS bonw15
Kernel: 6.18.7-76061807-generic
Resolution: 2560x1440
DE: COSMIC
CPU: Intel i9-14900HX (32) @ 5.800GHz
GPU: Intel Raptor Lake-S UHD Graphics
GPU: NVIDIA GeForce RTX 4080 Max-Q / Mobile
Memory: 17272MiB / 64138MiB
```

```
❯ nvidia-smi
Wed Mar 25 12:09:42 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.126.18             Driver Version: 580.126.18     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080 ...    Off |   00000000:02:00.0 Off |                  N/A |
| N/A   46C    P8              4W /  150W |       5MiB /  12282MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by Nishan-Vivek** [comment]
I just noticed a new displaylink driver available in the synamptics ubuntu repo. Unfortunately I'm away from my usual setup for next 5 days to see if resolves the issue. No change log on the synaptic site. 

displaylink-driver/stable 6.3.0-48 amd64 [upgradable from: 6.2.0-30]

**Comment by weberam2** [comment]
I just upgraded and rebooted. Still have the same issues

**Comment by Nishan-Vivek** [comment]
@weberam2 thanks for checking the new drivers so quickly. I found one more thing to try if you have the time. If not i'll give it a test this weekend. Apparently some other display issues with other graphics systems have been resolved with 

COSMIC_DISABLE_DIRECT_SCANOUT=y

https://github.com/pop-os/cosmic-comp/issues/2336

**Comment by weberam2** [comment]
I added a .sh file into /etc/profile.d:
`export COSMIC_DISABLE_DIRECT_SCANOUT=y`
then rebooted
I checked:
```
❯ echo $COSMIC_DISABLE_DIRECT_SCANOUT
y
```
but it didn't fix the issue :(

**Comment by Nishan-Vivek** [comment]
I was testing Ubuntu 26.04 on a usb stick when I found the unofficial Comsic desktop PPA. While Ubuntu-gnome worked perferectly on my portrait displaylink monitors the Cosmic desktop did not. So the issue is definitely  with Cosmic and not evdi, displaylink drivers, wayland etc.

**Comment by scottmckendry** [comment]
If it helps anyone trying to triage this issue - the problem is in smithay, no pop-os specifically.

The same issue exists on other smithay-based compositors, like niri.

**Comment by weberam2** [comment]
> If it helps anyone trying to triage this issue - the problem is in smithay, no pop-os specifically.
> 
> The same issue exists on other smithay-based compositors, like niri.

Interesting!

I'm surprised this is still not fixed

**Comment by mmstick** [comment]
@weberam2 We accept pull requests if you have a fix.

**Comment by Nishan-Vivek** [comment]
> If it helps anyone trying to triage this issue - the problem is in smithay, no pop-os specifically.
> 
> The same issue exists on other smithay-based compositors, like niri.

Good find, I should probably figure where to submit a bug report at the upstream project.

**Comment by scottmckendry** [comment]
This has been fixed upstream in Smithay:

https://github.com/Smithay/smithay/pull/2048

I'm running a custom build of niri built using the latest commit on Smithay's `master` branch and can confirm the damage issue on portrait displays is no longer present when using displaylink hardware.

I think it's safe to say the issue in COSMIC will also be fixed once Smithay has been updated to a version that includes the fix linked above.

**Comment by weberam2** [comment]
This is amazing news!

**Comment by Nishan-Vivek** [comment]
I just created a test install of pop_os 24 on a usb stick and can confirm the fix has made its way downstream. My portrait display-link monitors no longer had artifacts or issues. Awesome!
