### ISSUE TITLE
Resuming from suspend would result in audio outputs and inputs to be set to "Dummy Output" and "No Device Selected".

### ISSUE THREAD

**Issue by BugsyReportsy** [pop-os/cosmic-epoch#2580]
**Describe the bug**
After today's update, resuming from suspend would result in audio outputs and inputs to be set to "Dummy Output" and "No Device Selected". I would have to go into COSMIC Settings to set my audio back up after every resume, where all audio devices would have their profile set to "Off" by default.

**To Reproduce**
1. Suspend system that has multiple audio devices, it could any type of output or input set to any profile.
2. Resume system.

**Expected behavior**
Audio output and input settings are restored upon resume.

**Screenshots**

**Desktop (please complete the following information):**
 - Pop!_OS 24.04

**Additional context**
- Audio outputs/inputs with their profiles and volume settings are restored correctly after booting/rebooting into the OS.
- Plugging in any new audio device, such as a headset, would have its profile be set to "Off" by default.
- My kernel is 6.16.3. (I can't use 6.17.4 due to widely reported unrelated issues.)
- Setting any audio profile from "Off" to anything else results in the volume sliders being shown at 100, no matter what it's actually set at.

**Comment by externuz** [comment]
Same issue

**Comment by DracoTomes** [comment]
I'm on 24.04 LTS and the 6.17.4 kernel. Cosmic Settings > Sound and Device Profiles don't seem to persist through reboots. I have four audio devices most of which show up as "Off" after starting my machine.

**Comment by BugsyReportsy** [comment]
Update on the audio issues, it seems that COSMIC would sometimes randomly select a connected audio device upon resume, with every other device being set to "Off". The volume level indicated by COSMIC settings and the audio applet would also be mismatched with what it actually was, where only the volume OSD would show it correctly.

**Comment by interstellarvagabond** [comment]
I'm having the same or similar issue.  After restarting wireplumber, pipewire, and pipewire-pulse  as in the "Dummy Output" post on reddit my audio output devices now appear in sound settings, but the selection doesn't persist on leaving and reentering sound settings and there is no sound output regardless of the selection. 

I also don't get sound over bluetooth, although after some combination of toggling bluetooth, and rebooting and re-pairing my device I sometimes do.  Perhaps these issues are related.

Also, my issue doesn't seem to be correlated to suspending and occurs even fresh after a reboot.

**Comment by interstellarvagabond** [comment]
The latest update seems to have fixed the issue with sound profile settings not persisting and random audio device selection on reboot for me.   However, while I can select a persistent sound profile, output device selection still does not persist on switching out of and back into sound settings.

Also, when I successfully connect my bluetooth audio device, the audio output does not automatically switch to the bluetooth device and I have to manually select the bluetooth device via sound settings (which does persist in this case), and then back when I disconnect the device.  This could lead to rather embarrassing situations in a public setting!  Maybe this is a different bug, but it seems related.

**Comment by BugsyReportsy** [comment]
I also just installed tonight's updates, and while the audio devices themselves seem to work properly upon resume now. The audio applet still displays "No device selected" half of the time. Both the audio applet and COSMIC settings also still show the incorrect volume settings.

**Comment by dominix** [comment]
Also, when I turn on a bluetooth device the device connect automatically to my desktop OS but since a few days ago it is no more automatically selected, so the sound stay to the previous device. It was not the case before, the good behavior is to automatically select the Bluetooth device as soon as it connect.

**Comment by bobcat141** [comment]
I'm having the same issue when hibernating the system.

**Comment by cz4rr** [comment]
Same issue on Arch and Cachy. Downgrading cosmic-comp and cosmic-session to 1.0.0.beta.8-1 fixes the issue.
Used below cmd as a temporary workaround / fix:
systemctl --user restart pipewire.service pipewire-pulse.service wireplumber.service
You might need to reselect audio device in settings after this cmd.

**Comment by zarugo** [comment]
Same issue on Fedora 43 (packages from copr ryanabx/cosmic-epoch), although it does not seem to be specifically bound to suspend or hibernate. My machine does not suspend, but, when I leave it unattended (for how long, I am not sure), all the audio devices are gone. 
Restarting pipewire/wireplumber brings them back on the settings apllication, but the audio applet still does not show them, neither I can change the volume using XF86 keyboard mapping. Only a logout/login fixes it

**Comment by cz4rr** [comment]
> Same issue on Fedora 43 (packages from copr ryanabx/cosmic-epoch), although it does not seem to be specifically bound to suspend or hibernate. My machine does not suspend, but, when I leave it unattended (for how long, I am not sure), all the audio devices are gone. Restarting pipewire/wireplumber brings them back on the settings apllication, but the audio applet still does not show them, neither I can change the volume using XF86 keyboard mapping. Only a logout/login fixes it

Yes, can confirm, on my laptop FN audio key mappings also stop functioning

**Comment by dnazarov1** [comment]
Similar issue after the recent update beta 9. After reboot no audio devices until i reorganize them again from the profile picker in the audio settings.

**Comment by SharktoothActual** [comment]
+1 confirming as bug. CachyOS/Arch Linux on kernel 6.17.8, cosmic-session version 1.0.0.beta.9-1

Temporary workaround:

1. Open COSMIC Settings
2. Go to "Sound"
3. Go to "Device profiles"
4. Reconfigure your audio profiles

After that, sound should be working.

**Comment by BugsyReportsy** [comment]
> I also just installed tonight's updates, and while the audio devices themselves seem to work properly upon resume now. The audio applet still displays "No device selected" half of the time. Both the audio applet and COSMIC settings also still show the incorrect volume settings.

As of today, I'm still getting the visual bugs, where any audio device that's  just been plugged in or resumed from suspend, such as my headset most noticeably, gets shown to be at 100% volume for both output and input in the applet and settings.

**Comment by MakeShiftArtist** [comment]
I'm still encountering this issue on
Kernel: 6.18.0
cosmic-session-1.0.0-beta.9

On NixOS Unstable [2fbfb1d7](https://github.com/NixOS/nixpkgs/tree/2fbfb1d73d239d2402a8fe03963e37aab15abe8b)

On reboot or suspend it'll disable the audio profile that I use under "Sound" -> "Device Profiles". Instead of remembering the setting it was on, it automatically sets it to "Off" which forces me to re-enable it every time I reboot or suspend

<img width="941" height="466" alt="Image" src="https://github.com/user-attachments/assets/097f63ac-363e-4fdc-b062-d817adb01f80" />

All the devices show as "off"

<img width="907" height="292" alt="Image" src="https://github.com/user-attachments/assets/fc5ea588-5ce9-411a-9126-d6720aa44f05" />

**Comment by FF-AntiK** [comment]
I have a similar issue on Fedora Cosmic Atomic. Every reboot all device profiles are reset to "Off".

**Comment by dnazarov1** [comment]
looks like its fixed in the 1.0 release

**Comment by FF-AntiK** [comment]
> looks like its fixed in the 1.0 release

Just upgraded and I can confirm. It's fixed for me as well 👍🏼

**Comment by BugsyReportsy** [comment]
@leviport 
Why was this closed? I'm still facing the visual bugs, with the incorrect volume settings being shown, and the applet showing "No device selected" upon resume half the time.

**Comment by leviport** [comment]
People were saying it was fixed. I'll reopen it.

**Comment by MakeShiftArtist** [comment]
I can confirm the issue is resolved for me after updating to 1.0.0

- cosmic-comp-1.0.0
- cosmic-session-1.0.0
- cosmic-settings-1.0.0
- Kernel: 6.18.1

On nixos-unstable [c6245e8](https://github.com/NixOS/nixpkgs/tree/c6245e83d836d0433170a16eb185cefe0572f8b8)


I've tested both suspends and reboots.

**Comment by BugsyReportsy** [comment]
I'll test this again to confirm it's fixed on my end.

**Comment by BugsyReportsy** [comment]
> [@leviport](https://github.com/leviport) Why was this closed? I'm still facing the visual bugs, with the incorrect volume settings being shown, and the applet showing "No device selected" upon resume half the time.

Maybe this has been a separate bug this whole time.

**Comment by cz4rr** [comment]
I'm still facing this issue both on Laptop (Arch) and PC (CachyOS) - both up to date. 
No audio also happens on clean boot - PC.
On laptop this also messes up FN volume up and down keys - they stop working.
Any workarounds? Restarting audio stack helps: 
systemctl --user restart pipewire pipewire-pulse wireplumber

**Comment by cz4rr** [comment]
Looks like switching Device Profile to Pro Audio resolves issue on my laptop - using volume slider from audio applet no longer breaks audio in videos. FN keys keep working and audio OSD volume popup appears as usual. 

Previously using audio slider in applet immediately broke video playback - only restarting whole audio stack helped but slider no longer worked after and OSD did not appear anymore when using FN keys. 

Hope this helps.
