### ISSUE TITLE
Changing input language breaks shortcuts

### ISSUE THREAD

**Issue by zayats1** [pop-os/cosmic-epoch#2701]
**Describe the bug**
Global shortcuts that use letters on a keyboard  stopped working, after I changed my input language to Ukrainian.
The are working on KDE Plasma6 though.

**To Reproduce**
1) Go to the settings,keyboard
2) Add Ukrainian as the second input language
3) Select Ukrainian language
4) press SUPER + A or any letter on the keyboard
5) App library will not show

**Expected behavior**
SUPER + A -> App library

**Desktop (please complete the following information):**
 latest cosmic release on Arch Linux
**Additional context**
I have KDE  Plasma6 and Cosmic installed on my system.

**Comment by demon101** [comment]
Same with Russian language. All shortcuts works only on English

**Comment by maxus2004** [comment]
I also have this issue. I partially fixed it by manually adding shortcuts in a different keyboard layout in settings, but some shortcuts are hardcoded in cosmic apps and can't be modified this way.

**Comment by mmstick** [comment]
This should be fixed with the latest release. @maxus2004 What version of cosmic-comp do you have?

**Comment by maxus2004** [comment]
I haven't updated in 2 weeks. I am on arch linux, I will check now.

**Comment by maxus2004** [comment]
Ok, system shortcuts work as intended now. But in cosmic-edit (packaged in extra/cosmic-text-editor in Arch repos) shortcuts still don't work, i checked ctrl+A, ctrl+C and ctrl+V. Is the package just slightly outdated and everything should be fixed already?

**Comment by mmstick** [comment]
@maxus2004 Those will be specific to pop-os/libcosmic or cosmic-edit

**Comment by zayats1** [comment]
> Ok, system shortcuts work as intended now. But in cosmic-edit (packaged in extra/cosmic-text-editor in Arch repos) shortcuts still don't work, i checked ctrl+A, ctrl+C and ctrl+V. Is the package just slightly outdated and everything should be fixed already?

same situation.
