### ISSUE TITLE
`.local/share/applications/` doesn't replace `/usr/share/applications/`

### ISSUE THREAD

**Issue by XandrCopyrighted** [pop-os/cosmic-epoch#278]
Instead...

![screenshot-2024-04-25-04-04-35](https://github.com/pop-os/cosmic-epoch/assets/111686716/430001d1-ba79-4c93-a5e5-22d00e8fb086)

**Comment by atagen** [comment]
issue took me a minute to understand, maybe some clearer information like "User .desktop files duplicate instead of replacing system .desktop files" is better

**Comment by XandrCopyrighted** [comment]
alr

**Comment by XandrCopyrighted** [comment]
done

**Comment by XandrCopyrighted** [comment]
they need to also hide the .desktop for applications that aren't installed, but are still in `.local/share/applications/`

![image](https://github.com/pop-os/cosmic-epoch/assets/111686716/75e770d8-35a5-4694-814b-2aa67428f169)

**Comment by dimhollowcrypt** [comment]
This is still a problem, desktop entries in ~/.local/share/applications still generate duplicates when in other desktops they instead override the /usr/share/applications entry. A small correction though, what other desktops (I've only tried gnome) do is not check if an application "is installed", that's not really doable across every linux distro. What they seem to do instead is check if the Exec line actually resolves to a "valid" command, so if you have Exec=/foo/bar and /foo/bar doesn't exist it gets hidden in gnome, but if you have Exec=flatpak run foo.bar and flatpak itself is installed, then it will still appear at least in gnome, even though no such flatpak exists. Either way this is also something cosmic should probably do.

**Comment by pguyennet** [comment]
Up same problem still (here with Firefox). I should only see the local Firefox isntead of both

<img width="1309" height="732" alt="Image" src="https://github.com/user-attachments/assets/343d997a-2605-42b1-b6b1-a627dccbc678" />

**Comment by EAbuVrwV** [comment]
This problem also still happens when installing the Steam system package directly out of the Pop Shop.
