### ISSUE TITLE
[BUG] Reaper DAW menu bar not responsive

### ISSUE THREAD

**Issue by GoranKovac** [pop-os/cosmic-epoch#444]
Clicking on any entry in menu bar does not open dropdown. 
![Imgur Image](https://i.imgur.com/Bpjx1nL.png)

Also on some parts of the app (mainly Track Control Panel segment on the left side) the cursor size is increased for some reason.
https://www.reaper.fm/

**Comment by xchinox** [comment]
I am getting similar behavior on Fedora 40 using the COPR build. perhaps worth mentioning is that the menus are working and interactive but invisible. If I know where to click or what navigation keys to use I am able to operate the menus. For now I am forced to run reaper in a gamescope session.

Perhaps unrelated but I had similar cursor size issues in the past solved by setting the XCURSOR_SIZE environment variable.

**Comment by GoranKovac** [comment]
Still issue in Alpha 2

**Comment by markHadman** [comment]
Still an issue in Alpha 4

**Comment by NicolasPetton** [comment]
I'm having the same issue in Alpha 5

**Comment by mechatour** [comment]
Hi, just to update, this is still an issue for my in Alpha 6

**Comment by GoranKovac** [comment]
Yeah still not fixed, but as I seen this is not the only app with this issue

**Comment by mechatour** [comment]
I wonder if this is the same framework in both apps?

**Comment by travis-aaron** [comment]
I didn't see this issue for whatever reason, added a few additional details over at #1409

**Comment by GoranKovac** [comment]
> I didn't see this issue for whatever reason, added a few additional details over at [#1409](https://github.com/pop-os/cosmic-epoch/issues/1409)

There is another thing, if you install Imgui extension for it (via reapack https://reapack.com/) any imgui window is not movable

**Comment by GoranKovac** [comment]
Fixed in alpha 7!

**Comment by troll-os** [comment]
Still an issue for me, Pop_OS up to date + cosmic and latest version of Reaper (7.42)
