### ISSUE TITLE
Missing Signed-By Field in Sources List Causes APT Update Errors on Pop!_OS Alpha

### ISSUE THREAD

**Issue by ERLindeman** [pop-os/cosmic-epoch#516]
In the Pop!_OS 24.04 Alpha release, users may encounter errors during apt update or apt upgrade operations due to missing Signed-By fields in the sources list entries for Pop!_OS and Ubuntu repositories. This issue prevents the system from securely accessing the repositories, leading to warnings or errors that can hinder package management.

Steps to Reproduce:

1. Install Pop!_OS 24.04 Cosmic Epoch 1 Alpha.
2. Open a terminal and run:
`sudo apt update`
3. Observe the following error messages:
```N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/proprietary'
N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/release'
N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/ubuntu'
N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/ubuntu'
N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/ubuntu'
N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/ubuntu'
```
Resolution:
To resolve this issue, the relevant entries in the sources list files must be updated to include the Signed-By field pointing to the correct GPG keyring file. Below are the detailed steps to fix this issue:

1. Run the following command to identify the files that reference the problematic repositories:
`grep -r 'apt.pop-os.org' /etc/apt/sources.list.d/`
2. For each identified file, follow the steps below:
- Open the File: `sudo nano /etc/apt/sources.list.d/FILE_NAME_HERE`
- Append the Signed-By Field to end of file: `Signed-By: /etc/apt/trusted.gpg.d/pop-keyring-2017-archive.gpg`
- Save and exit

3. Confirm resolution
```sudo apt update
sudo apt upgrade
```

Can we modify the shipped image to prevent this error from happening on other installs?

**Comment by davidmhendrix** [comment]
Same issue here on freshly downloaded iso.  I'm doing this on a 2012 iMac with the nvidia distro - not sure if same on amd/intel.

**Comment by PolarisPyra** [comment]
I also had the same issue im on intel/nvidia I hope this gets looked at :D if i apply the fix it works but i now get warnings

`W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/ubuntu noble InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/ubuntu noble-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/ubuntu noble-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/ubuntu noble-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://apt.pop-os.org/ubuntu/dists/noble/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://apt.pop-os.org/ubuntu/dists/noble-security/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://apt.pop-os.org/ubuntu/dists/noble-updates/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://apt.pop-os.org/ubuntu/dists/noble-backports/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by JJarratt** [comment]
Same issue for me.  Applying:

`
Signed-By: /etc/apt/trusted.gpg.d/pop-keyring-2017-archive.gpg`

Seems to resolve the error for

/etc/apt/sources.list.d/pop-os-apps.sources
/etc/apt/sources.list.d/pop-os-release.sources

but not 

/etc/apt/sources.list.d/system.sources

**Comment by robinlefleur** [comment]
To fix the NO_PUBKEY issue I had to manually delete the repositories and add them again using their website

https://apt.pop-os.org/

**Comment by HeCodes2Much** [comment]
> Same issue for me. Applying:
> 
> ` Signed-By: /etc/apt/trusted.gpg.d/pop-keyring-2017-archive.gpg`
> 
> Seems to resolve the error for
> 
> /etc/apt/sources.list.d/pop-os-apps.sources /etc/apt/sources.list.d/pop-os-release.sources
> 
> but not
> 
> /etc/apt/sources.list.d/system.sources

`Signed-By:  /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg`

this should fix that

**Comment by jackpot51** [comment]
May be fixed by: https://github.com/pop-os/iso/commit/2b7353d41145ded59030c075ce76481d4b17367d

**Comment by HeCodes2Much** [comment]
> May be fixed by: [pop-os/iso@2b7353d](https://github.com/pop-os/iso/commit/2b7353d41145ded59030c075ce76481d4b17367d)

UBUNTU_KEY is not set in the .mk file

**Comment by HeCodes2Much** [comment]
> May be fixed by: [pop-os/iso@2b7353d](https://github.com/pop-os/iso/commit/2b7353d41145ded59030c075ce76481d4b17367d)

that should fix it 👍

**Comment by spcutrell** [comment]
Stupid question - do I need to do anything for that fix to work? I'm still getting the error on a freshly DL'd Cosmic  (Nvidia) ISO.

**Comment by Android789515** [comment]
I'm still getting the erros on an up to date Cosmic Epoch system.

**Comment by ismailkarsli** [comment]
Are we going to get this fix automatically or should we manually fix?

**Comment by Department-stack** [comment]
I believe it was already fixed in the newest iso. I am not sure if it is applied automatically to existing systems  that are updated. but if it isn't then you may need to apply the fix yourself or reinstall using the new iso

**Comment by Android789515** [comment]
I tried the fix mentioned by the OP and now I get more errors:

```
Hit:2 http://apt.pop-os.org/proprietary noble InRelease
Hit:1 https://packages.microsoft.com/repos/code stable InRelease
Hit:3 http://apt.pop-os.org/release noble InRelease
Hit:4 http://apt.pop-os.org/ubuntu noble InRelease
Err:4 http://apt.pop-os.org/ubuntu noble InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Hit:5 http://apt.pop-os.org/ubuntu noble-security InRelease
Hit:6 http://apt.pop-os.org/ubuntu noble-updates InRelease
Err:5 http://apt.pop-os.org/ubuntu noble-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Hit:7 http://apt.pop-os.org/ubuntu noble-backports InRelease
Hit:8 https://ppa.launchpadcontent.net/maveonair/helix-editor/ubuntu noble InRelease
Err:6 http://apt.pop-os.org/ubuntu noble-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Hit:9 https://ppa.launchpadcontent.net/openrazer/stable/ubuntu noble InRelease
Err:7 http://apt.pop-os.org/ubuntu noble-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Hit:10 https://ppa.launchpadcontent.net/polychromatic/stable/ubuntu noble InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/ubuntu noble InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/ubuntu noble-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/ubuntu noble-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/ubuntu noble-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://apt.pop-os.org/ubuntu/dists/noble/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://apt.pop-os.org/ubuntu/dists/noble-security/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://apt.pop-os.org/ubuntu/dists/noble-updates/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://apt.pop-os.org/ubuntu/dists/noble-backports/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by jacobgkau** [comment]
> I have spent hours setting this system up, not going to reinstall we need a working quick fix.

This is an alpha. Do not spend hours doing anything on it that you aren't willing to do again.

**Comment by qs5779** [comment]
I realize it is alpha, and I am fine with a reinstall when/if needed, but not for something trivial to fix manually.

**Comment by farhatizakaria** [comment]
I have added `Signed-By: /etc/apt/trusted.gpg.d/pop-keyring-2017-archive.gpg` to those files, but I got more errors (the iso downloaded and installed at 19/08/2024):

```
Hit:2 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:3 http://apt.pop-os.org/proprietary noble InRelease
Hit:4 http://apt.pop-os.org/release noble InRelease
Hit:5 http://apt.pop-os.org/ubuntu noble InRelease
Err:5 http://apt.pop-os.org/ubuntu noble InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Hit:6 http://apt.pop-os.org/ubuntu noble-security InRelease
Err:6 http://apt.pop-os.org/ubuntu noble-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Hit:7 http://apt.pop-os.org/ubuntu noble-updates InRelease
Err:7 http://apt.pop-os.org/ubuntu noble-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Hit:8 http://apt.pop-os.org/ubuntu noble-backports InRelease
Err:8 http://apt.pop-os.org/ubuntu noble-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Hit:1 https://packages.microsoft.com/repos/code stable InRelease
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/ubuntu noble InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/ubuntu noble-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/ubuntu noble-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/ubuntu noble-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://apt.pop-os.org/ubuntu/dists/noble/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://apt.pop-os.org/ubuntu/dists/noble-security/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://apt.pop-os.org/ubuntu/dists/noble-updates/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://apt.pop-os.org/ubuntu/dists/noble-backports/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by mmstick** [comment]
It's only a warning, so it's not necessary to fix manually.

**Comment by jacobgkau** [comment]
The warnings in the last few comments are about `http://apt.pop-os.org/ubuntu` (the Ubuntu mirror), not `http://apt.pop-os.org/release` (the Pop!_OS repo).

If you look at the iso PR, `pop-keyring-2017-archive.gpg` was not the only file added. There's also an `ubuntu-keyring-2018-archive.gpg` file added. I think that's what's missing on the system for people getting those particular warnings.

**Comment by Android789515** [comment]
> The warnings in the last few comments are about `http://apt.pop-os.org/ubuntu` (the Ubuntu mirror), not `http://apt.pop-os.org/release` (the Pop!_OS repo).
> 
> If you look at the iso PR, `pop-keyring-2017-archive.gpg` was not the only file added. There's also an `ubuntu-keyring-2018-archive.gpg` file added. I think that's what's missing on the system for people getting those particular warnings.

Thank you, applying that fixed the rest of the errors.

**Comment by farhatizakaria** [comment]
I'm sorry @jacobgkau would please clarify to me? should I append these lines:
```
Signed-By:  /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg
Signed-By: /etc/apt/trusted.gpg.d/pop-keyring-2017-archive.gpg
```

to the following files: **system.sources**, **pop-os-release.sources** and **pop-os-apps.sources** ??

**Comment by jacobgkau** [comment]
You need `pop-keyring-2017-archive.gpg` in `pop-os-release.sources` and `pop-os-apps.sources`, and you need `ubuntu-keyring-2018-archive.gpg` in `system.sources`.

**Comment by farhatizakaria** [comment]
@jacobgkau Thank you, applying them fixed the the errors.

**Comment by Nora-Noo** [comment]
I made a GitHub account to thank you all very much!

**Comment by PerfMonk** [comment]
Just upgraded to pop!_OS 24.04 from 22.04 and got the same problem.  But after adding Signed-By field, I now get messages that there is  NO_PUBKEY  available. Repository not updated.

**Comment by jackpot51** [comment]
@mmstick I think this is fixed in the ISO but not when upgrading.

**Comment by PerfMonk** [comment]
Could it be corrected with an update for those who upgraded and did not install from the iso ???  Or just publish a solution ???

**Comment by mmstick** [comment]
@PerfMonk Yes, an update to the default-settings package will insert the field if it is missing.

**Comment by sahlie1985** [comment]
I fixed it by add 
_Signed-By: /etc/apt/trusted.gpg.d/pop-keyring-2017-archive.gpg_
on the 2 file 
_/etc/apt/sources.list.d/pop-os-apps.sources
/etc/apt/sources.list.d/pop-os-release.sources_
and i added 
_Signed-By:  /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg_
on file 
_/etc/apt/sources.list.d/system.sources_

**Comment by BugsyReportsy** [comment]
I just had this issue with current beta version, and was able to fix it by going into Repoman, then turning off and on the universe, restricted, and multiverse toggles.

**Comment by BugsyReportsy** [comment]
I just had this issue on Epoch 1 stable release, and the only way I could fix it was using Timeshift to restore to a backup that was made before today. Everything in ` /etc/apt/sources.list.d/pop-os-apps.sources`, ` /etc/apt/sources.list.d/pop-os-release.sources`, and ` /etc/apt/sources.list.d/system.sources` were configured as they were supposed to be, yet I still get `N: Missing Signed-By in the sources.list(5) entry for 'http://apt.pop-os.org/ubuntu'` out of the blue for seemingly no reason.

**Comment by KodeBarista** [comment]
> I just had this issue with current beta version, and was able to fix it by going into Repoman, then turning off and on the universe, restricted, and multiverse toggles.

This worked, Thanks!

**Comment by MMaicki** [comment]
### Possible FIX:

**Identify the Source File**
The configuration is likely located in /etc/apt/sources.list.d/system.sources. 
Use cat to inspect it:

`cat /etc/apt/sources.list.d/system.sources`

**Verify GPG Key Location:**
`ls /usr/share/keyrings/ubuntu-archive-keyring.gpg`

`sudo vi /etc/apt/sources.list.d/system.sources`

**Change Singed-By line to**
`Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg`

**Run this command to find any other file mentioning the Ubuntu mirror:**

`grep -r "apt.pop-os.org/ubuntu" /etc/apt/sources.list.d/`

**Open the main configuration file:**

`cat /etc/apt/sources.list`

If this file contains lines starting with deb [http://apt.pop-os.org/ubuntu](http://apt.pop-os.org/ubuntu), they are redundant and lack the Signed-By attribute.

**Action:**
If /etc/apt/sources.list is not empty and contains those URLs, comment them out by adding a # at the start of each line, or clear the file if it only contains the redundant Pop!_OS/Ubuntu lines:

`sudo truncate -s 0 /etc/apt/sources.list`

**Clear APT state**

Sometimes APT retains notices in its internal cache. Clear the lists and re-fetch:
Bash

```
sudo rm -rf /var/lib/apt/lists/*
sudo apt update
```

**Comment by nicheath** [comment]
@MMaicki 

```
Clear APT state

Sometimes APT retains notices in its internal cache. Clear the lists and re-fetch:
Bash

sudo rm -rf /var/lib/apt/lists/*
sudo apt update
```

Thank you. This did it for me on PopOS_24.04.
