### ISSUE TITLE
[Bug] Bluetooth turns on at wake

### ISSUE THREAD

**Issue by Ishmal7** [pop-os/cosmic-epoch#551]
After toggling Bluetooth off and suspending the system, Bluetooth has been turned back on upon login.

**Comment by Pentaphon** [comment]
I have the same issue. Not sure why the toggle won't stay off.

**Comment by colossus73** [comment]
I confirm the bug in 24.04 alpha 4.

**Comment by digitalethics** [comment]
Related: https://github.com/pop-os/cosmic-applets/issues/430

**Comment by ARez2** [comment]
I noticed that when I run `service bluetooth status` after turning off Bluetooth via the applet, that I get an error message in the logs displayed for each time I try to turn BT off:
`pop-os bluetoothd[27888]: src/adv_monitor.c:btd_adv_monitor_power_down() Unexpected NULL btd_adv_monitor_manager object upon power down`

This might be a hint, that even though the applet shows Bluetooth being off, its not actually getting turned off because of that error.

**Comment by ARez2** [comment]
Maybe that helps, but I discovered that for the cosmic applet, there isn't an error after toggling bluetooth, at least at this highlighted line, there arrives no error:
https://github.com/pop-os/cosmic-applets/blob/f4f7d990d8d3682f7158f75a2af625e86af67d7b/cosmic-applet-bluetooth/src/bluetooth.rs#L618

**Comment by ARez2** [comment]
Heres the output of `bluetoothctl show`:
```
Controller 14:AC:60:29:XX:XX (public)
	Manufacturer: 0x0046 (70)
	Version: 0x0b (11)
	Name: pop-os
	Alias: pop-os
	Class: 0x006c010c (7078156)
	Powered: yes
	Discoverable: no
	DiscoverableTimeout: 0x000000b4 (180)
	Pairable: no
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: Handsfree Audio Gateway   (0000111f-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
	UUID: Audio Source              (0000110a-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
	UUID: Handsfree                 (0000111e-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v1D6Bp0246d0548
	Discovering: no
	Roles: central
	Roles: peripheral
Advertising Features:
	ActiveInstances: 0x00 (0)
	SupportedInstances: 0x14 (20)
	SupportedIncludes: tx-power
	SupportedIncludes: appearance
	SupportedIncludes: local-name
	SupportedSecondaryChannels: 1M
	SupportedSecondaryChannels: 2M
	SupportedSecondaryChannels: Coded
```

**Comment by leviport** [comment]
Is this still happening? On my Oryx and my Dev One, bluetooth is staying off after a suspend and resume.

**Comment by leviport** [comment]
I think this is fixed.

**Comment by om1cmd** [comment]
This issue is still happening on my laptop on up to date Pop!_OS. I noticed that version of cosmic-applets is 1.0.2 rather than 1.0.7 (output of apt list `cosmic-applets/noble,now 1.0.2~1771347162~24.04~eb8784b amd64 [installed,automatic]`). I would assume that it should be 1.0.7 but it isn't. Is this supposed to be this way?
