### ISSUE TITLE
Window focus don't navigate between monitors anymore

### ISSUE THREAD

**Issue by Thatoo** [pop-os/cosmic-epoch#902]
In case it is an upstream issue, I open [this issue](https://github.com/lilyinstarlight/nixos-cosmic/issues/310) here also : 

Untill yesterday I updated, when I was navigating between windows with Super + left or Super + right, the focus was switching from window to window. It still works today between windows within one monitor but once it reaches the edge of a monitor (let say last right window of the first monitor, left monitor) and it supposes to switch to the next window, the first one on the next monitor (left side of the right monitor), typing Super + right, then it does not work anymore.
The focus remain on the last window of the first monitor, on the right window of the left monitor (I can keep writing in it instead of typing in the next window as expected).
The second (right) monitor has been selected though as I can switch workspace within this second monitor (even though the focus is still on first monitor). If I "come back" to the last window of the first monitor (typing Super + left then), then focus remain to the same window as if it had indeed come back and I can now switch workspace of the first monitor and I need to type again Super + left to move to other window between the first monitor.

**Comment by Thatoo** [comment]
Moving window between monitor still works.

**Comment by candsastle** [comment]
I can confirm that this problem exists. Also, swapping windows between monitors doesn't work either.

**Comment by Thatoo** [comment]
Well, for me this issue has been solved recently, after some update.

**Comment by candsastle** [comment]
> Well, for me this issue has been solved recently, after some update.

I'm still on Alpha 2 (Arch) but I'm glad it's since been resolved.

**Comment by candsastle** [comment]
Actually nevermind, this is still an issue on Cosmic Alpha 3. I still can't navigate or swap windows between monitors. 
The only improvement is that if I try to navigate to a window on a different monitor, then press the Super key to bring up the Launcher, the Launcher appears on the correct monitor (the one I wanted to go to). Dismissing the launcher returns focus to the target monitor. So technically I can navigate to windows between monitors, but only if I invoke and dismiss the launcher as intermediate steps, which is obviously undesirable.

**Comment by candsastle** [comment]
Ok so update: I got this issue fixed by simply changing my Workspaces > Multi-monitor Behavior from "Workspaces Span Displays" to "Displays Have Separate Workspaces". I can now properly navigate between different different monitors and even swap windows between monitors. I'm not quite sure why this only works when each monitor is its own workspace, but at least I can finally use my desktop the way I like.

**Comment by user12257** [comment]
I have the same issue. And I do have my Multi-Monitor Behavior set to "Displays Have Separate Workspaces"

I have Super + hjkl to navigate the window focus. I don't want this to swap workspace, when on the edge, just jump over to the window to the left/right on the other monitor. From what I understand that is the behavior that you guys have right?

I can only switch focus to the next monitor with Super + Alt +hjkl, but that is less intuitive for me.

**Comment by HalibutGitWiz** [comment]
I have the same issue but found an easy way to work around it : set workspaces to span displays and your workspace orientation in the opposite direction as your monitors layout.

I have two monitors layed out horizontally and Super+hjkl to navigate between windows. With a vertical workspace orientation, only Super+jk may switch workspaces, but Super+hl won't, and those are the shorctus I use to navigate from one monitor to the other.
